### ISSUE TITLE
Adding charging power info to the map and data table?

### ISSUE THREAD

**Issue by weilinzung** [kdwink/supercharge.info#38]
Can we have the charging power info?

xxx Superchargers, available xxx, **up to 120kW**

https://supercharge.info/map
https://supercharge.info/data

**Comment by weilinzung** [comment]
Just check the data that already has the `powerKilowatt` key, so can we have one more column to show that? It would be very useful.

**Comment by jeffwilcox** [comment]
FYI I've also implemented the power into on the map view in PR #45 

Here's a screenshot of what that looks like... it's a little cluttered, but "bright red" is V3, gray outline is urban, the existing icons are the same red dot for standard chargers, and those outlined in a white halo are those without curated/known power levels.

<img width="1250" alt="Screen Shot 2019-12-15 at 4 25 26 PM" src="https://user-images.githubusercontent.com/427913/70871928-c4596f00-1f58-11ea-9b8f-c0a6cf3e1b4e.png">

**Comment by jeffwilcox** [comment]
FYI per @paulkva he would prefer white border on chargers for urban, gray for uncurated/unknown. Looking for additional input.

**Comment by paulkva** [comment]
I've implemented a small change to the title text that pops up when you hover over a marker, which I think will go well along with the icon changes.
![image](https://user-images.githubusercontent.com/313702/70969909-0d99e380-206b-11ea-8499-01ece41f3295.png)
What do you all think? I'd be happy to submit another pull request for it -- it won't conflict with either one that's currently open.

**Comment by jeffwilcox** [comment]
@paulkva I'm supportive, but I'm new to learning about this project and how decisions are made!

**Comment by paulkva** [comment]
It's a relatively small project in terms of contributors, with very few PRs overall. At this stage I think it's up to @kdwink entirely. I just got notified of your PRs as a past contributor and figured it wouldn't hurt to offer an opinion or two. :-)
